# -*- coding: utf-8 -*-
"""DeepFakeDetector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hl9fhgG_fam275EILNGNjoKODZATSPbQ

# Deepfake Detection

Rahul Champaneria and Jonathan Manzano

Department of Computer Science, San Jose State University

CS 171: Introduction to Machine Learning

Dr. Saptarshi Sengupta

2024 December 08

## Import Libraries
"""

import os
from pathlib import Path

from google.colab import drive

"""## Mount Google Drive"""

drive.mount('/content/drive')

"""## Cloned DF40 Repo

[DF40 GitHub Repository](https://github.com/YZY-stack/DF40)

## Declare Assign Path Variables
"""

project_root = Path('/content/drive/MyDrive/deepfake_detection_project/')
datasets_path = project_root / 'datasets'
df40_github_repo = project_root / 'df40'

"""## Change Working Directory"""

os.chdir(df40_github_repo)

"""## Run DF40 Installation Script

Installs necessary Python packages.
"""

!chmod +x install.sh
!./install.sh

"""## Run Inferences"""

os.chdir('./DeepfakeBench_DF40')

"""### Add `builder` module to `google.protobuf`

Source: [Stack Overflow](https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal)
"""

# Commented out IPython magic to ensure Python compatibility.
# %ls -al /usr/local/lib/python3.10/dist-packages/google/protobuf/internal

# Commented out IPython magic to ensure Python compatibility.
# %cp builder.py /usr/local/lib/python3.10/dist-packages/google/protobuf/internal
# %ls -al /usr/local/lib/python3.10/dist-packages/google/protobuf/internal

"""## Exisiting Models

*   Xception
*   CLIP
*   SRM
*   SPSL
*   RECCE
*   RFM

## Pretrained on Faceswap types

### Xception
"""

!python training/test.py --detector_path training/config/detector/xception.yaml \
--weights_path training/df40_weights/train_on_fs/xception.pth \
--test_dataset blendface_ff

"""### CLIP"""

!python training/test.py --detector_path training/config/detector/clip.yaml \
--weights_path training/df40_weights/train_on_fs/clip_large.pth \
--test_dataset blendface_ff

"""### SRM"""

!python training/test.py --detector_path training/config/detector/srm.yaml \
--weights_path training/df40_weights/train_on_fs/srm.pth \
--test_dataset blendface_ff

"""### RECCE"""

!python training/test.py --detector_path training/config/detector/recce.yaml \
--weights_path training/df40_weights/train_on_fs/recce.pth \
--test_dataset blendface_ff

"""### RFM"""

!python training/test.py --detector_path training/config/detector/rfm.yaml \
--weights_path training/df40_weights/train_on_fs/rfm.pth \
--test_dataset blendface_ff

"""### SPSL"""

!python training/test.py --detector_path training/config/detector/spsl.yaml \
--weights_path training/df40_weights/train_on_fs/spsl.pth \
--test_dataset blendface_ff
